# Generated by Django 6.0.3 on 2026-07-15 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer_admin', '0001_initial'),
        ('users', '0003_user_referred_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_users', to='offer_admin.referralcode'),
        ),
    ]
