# Generated by Django 6.0.7 on 2026-08-04 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checkout_page', '0001_initial'),
        ('order_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripepayment',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stripe_payment', to='order_user.order'),
        ),
    ]
