# Generated by Django 6.0.3 on 2026-04-10 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
