# Generated by Django 6.0.3 on 2026-04-10 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_user', '0002_cart_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='user_id',
            new_name='user',
        ),
    ]
