# Generated by Django 6.0.7 on 2026-08-04 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coupon_admin', '0001_initial'),
        ('order_user', '0001_initial'),
        ('product_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='products',
            field=models.ManyToManyField(blank=True, to='product_admin.product'),
        ),
        migrations.AddField(
            model_name='couponusage',
            name='coupon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='coupon_admin.coupon'),
        ),
        migrations.AddField(
            model_name='couponusage',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon_usages', to='order_user.order'),
        ),
    ]
