# Generated by Django 6.0.3 on 2026-04-02 06:45

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('product_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
