# Generated by Django 6.0.3 on 2026-04-14 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_listed',
            field=models.BooleanField(default=True),
        ),
    ]
