# Generated by Django 6.0.3 on 2026-05-16 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Sneakers', 'Sneakers'), ('Heels', 'Heels'), ('Flats', 'Flats'), ('Boots', 'Boots'), ('Sandals', 'Sandals'), ('Loafers', 'Loafers'), ('Sports Shoes', 'Sports Shoes'), ('Casual Shoes', 'Casual Shoes')], max_length=50),
        ),
    ]
