# Generated by Django 6.0.3 on 2026-07-13 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_admin', '0002_productreview_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
