# Generated by Django 6.0.3 on 2026-05-01 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_admin', '0002_product_is_blocked_product_is_listed'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
