# Generated by Django 6.0.3 on 2026-05-01 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_admin', '0003_product_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_shop_active',
            field=models.BooleanField(default=True),
        ),
    ]
