# Generated by Django 6.0.3 on 2026-05-27 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_user', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='razorpaytransaction',
            name='status',
            field=models.CharField(choices=[('created', 'created'), ('paid', 'paid'), ('failed', 'failed'), ('refunded', 'refunded')], default='created', max_length=20),
        ),
    ]
