# Generated by Django 6.0.7 on 2026-08-04 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offer_admin', '0001_initial'),
        ('product_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseoffer',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='offers', to='product_admin.product'),
        ),
        migrations.AddField(
            model_name='userofferusage',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_usage', to='offer_admin.baseoffer'),
        ),
    ]
