# Generated by Django 6.0.7 on 2026-08-05 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer_admin', '0003_initial'),
    ]

    operations = [
    ]
