# Generated by Django 6.0.7 on 2026-08-05 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer_admin', '0004_seed_referral_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseoffer',
            name='offer_type',
            field=models.CharField(choices=[('PRODUCT', 'Product Offer'), ('CATEGORY', 'Category Offer')], max_length=20),
        ),
    ]
