# Generated by Django 6.0.3 on 2026-05-19 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='reference',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='reason',
            field=models.CharField(choices=[('order_cancellation', 'Order Cancellation Refund'), ('order_return', 'Order Return Refund'), ('order_payment', 'Order Payment'), ('manual_adjustment', 'Manual Adjustment'), ('refund', 'Refund')], default='MANUAL', max_length=20),
        ),
    ]
