# Generated by Django 6.0.7 on 2026-08-10 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wallet',
            options={'verbose_name': 'Wallet', 'verbose_name_plural': 'Wallets'},
        ),
        migrations.RemoveField(
            model_name='wallettransaction',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='wallettransaction',
            name='user',
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='reason',
            field=models.CharField(choices=[('ORDER_CANCEL', 'Order Cancelled'), ('ORDER_RETURN', 'Order Returned'), ('ORDER_PAYMENT', 'Wallet Payment'), ('ADMIN_CREDIT', 'Admin Credit'), ('ADMIN_DEBIT', 'Admin Debit'), ('REFERRAL', 'Referral Bonus'), ('WELCOME', 'Welcome Bonus'), ('MANUAL', 'Manual')], default='MANUAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit')], max_length=10),
        ),
    ]
