# Generated by Django 6.0.3 on 2026-06-25 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_user', '0002_alter_wallet_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='reason',
            field=models.CharField(choices=[('purchase', 'Purchase'), ('cancellation', 'Cancellation'), ('return', 'Return'), ('referral', 'Referral'), ('manual', 'Manual Adjustment'), ('order', 'Order')], default='manual', max_length=20),
        ),
    ]
