# Generated by Django 6.0.3 on 2026-05-20 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_user', '0002_wallettransaction_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='reason',
            field=models.CharField(choices=[('order_cancellation', 'Order Cancellation Refund'), ('order_return', 'Order Return Refund'), ('order_payment', 'Order Payment'), ('manual_adjustment', 'Manual Adjustment'), ('refund', 'Refund')], default='manual_adjustment', max_length=20),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=10),
        ),
    ]
