# Generated by Django 6.0.3 on 2026-07-11 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='line_total',
        ),
    ]
