# Generated by Django 6.0.3 on 2026-06-04 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='phonepe_payment_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phonepe_response',
        ),
        migrations.AlterField(
            model_name='order',
            name='coupon_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
