# Generated by Django 6.0.3 on 2026-07-11 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_user', '0002_remove_orderitem_line_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='line_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
