# Generated by Django 6.0.3 on 2026-05-06 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_user', '0003_alter_order_return_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='return_reason',
            field=models.CharField(blank=True, choices=[('wrong_size', 'Wrong size received'), ('wrong_item', 'Wrong item received'), ('defective', 'Defective / damaged product'), ('not_as_described', 'Not as described'), ('changed_mind', 'Changed my mind'), ('quality_issue', 'Quality not as expected'), ('other', 'Other')], max_length=30, null=True),
        ),
    ]
