# Generated by Django 6.0.3 on 2026-07-14 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_user', '0003_orderitem_line_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='brand',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
