# Generated by Django 6.0.3 on 2026-05-06 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_user', '0004_alter_order_return_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='return_notes',
            field=models.TextField(blank=True),
        ),
    ]
