# Generated by Django 6.0.3 on 2026-05-20 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_user', '0005_alter_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='paypal_capture_id',
            new_name='razorpay_order_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='paypal_order_id',
            new_name='razorpay_payment_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='paypal_payer_id',
        ),
        migrations.AddField(
            model_name='order',
            name='razorpay_signature',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
