# Generated by Django 6.0.3 on 2026-05-14 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_user', '0007_order_razorpay_order_id_order_razorpay_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='razorpay_signature',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
