# Generated by Django 6.0.3 on 2026-05-16 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnProofImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='return_proofs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_reason', models.CharField(blank=True, choices=[('wrong_size', 'Wrong size received'), ('wrong_item', 'Wrong item received'), ('defective', 'Defective / damaged product'), ('not_as_described', 'Not as described'), ('changed_mind', 'Changed my mind'), ('quality_issue', 'Quality not as expected'), ('other', 'Other')], max_length=30, null=True)),
                ('return_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=15)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='order_user.order')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='order_user.orderitem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
