# Generated by Django 6.0.3 on 2026-05-06 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('return_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='return_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='return_reason',
            field=models.CharField(blank=True, choices=[('wrong_size', 'Wrong size received'), ('wrong_item', 'Wrong item received'), ('defective', 'Defective / damaged product'), ('not_as_described', 'Not as described'), ('changed_mind', 'Changed my mind'), ('quality_issue', 'Quality not as expected'), ('other', 'Other')], max_length=30, null=True),
        ),
    ]
