# Generated by Django 6.0.3 on 2026-03-31 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category_admin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='is_deleted',
            new_name='is_blocked',
        ),
    ]
