# Generated by Django 6.0.3 on 2026-03-31 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category_admin', '0002_rename_is_deleted_category_is_blocked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='is_blocked',
            new_name='is_deleted',
        ),
    ]
